### ISSUE TITLE
New theme without bold

### ISSUE THREAD

**Issue by vanessamilagres** [hiukky/flate#4]
You can create new themes like:
- italic
- regular

**Comment by ismailrubad** [comment]
Selected file is not highlighted in sidebar.

**Comment by hiukky** [comment]
@ismailrubad Thank you. correction soon.

**Comment by hiukky** [comment]
Hello @vanessamilagres and @ismailrubad! I just released version 0.6.0 with the new font styles for VS Code and with fixes for the mentioned problems.

I'm closing this issue, hug!
